apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: webapp
  labels:
    name: webapp
spec:
  containers:
  - name: webapp
    image: docker.io/mjura/webapp:03122024-rc.2
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
